### ISSUE TITLE
estimated runtime?

### ISSUE THREAD

**Issue by MrBurnst** [rousseau/BrainGrowth#2]
Hello! I tried running your code (on sphere5.mesh), and it produced the figure at t=0 and kept running (using 4 cores), but I killed it after 3 days because nothing appeared. What is the expected runtime (on modern hardware) of the example simulation.py ? 
thanks!

**Comment by x17wang** [comment]
Hi! The code iterates 500 steps every 3 minutes and outputs a file. It takes about 4h30min to run a simulation with sphere5.mesh to end. You can change the parameters "rho" or "dt" to run the simulation faster or slower.
Regards,
Xiaoyu.

**Comment by MrBurnst** [comment]
thanks! I found the problem - I'm getting negative eigenvalues in the estimation of the elasticity (tetraElasticity), because of very large values for the deformed configuration of the tetrahedra (At > 1e30), which causes NaNs to appear everywhere and crashes the code (when disabling jit) respectively causes the compiled code to get stuck without raising any errors.

I tried reducing the time-step by a factor 10 (0.005*np.sqrt(...)), but I got very weird-looking results (after 1500 iterations:)

![B1500](https://user-images.githubusercontent.com/4426897/58326325-c75e0800-7e2c-11e9-9749-c145cd23010f.png)

maybe I'm using the wrong sphere5? Maybe the parameters in simulation.py are not correct for sphere5?

**Comment by MrBurnst** [comment]
... any help?

**Comment by x17wang** [comment]
Hi，

Sorry，I have looked at it，if you have reduced the time-step by
10（0.05->0.005),  it doesn’t seem to show the result like that.  Did you
want to say that you increased the time-step？ Or you have changed some
parameters in simulation.py？It’s the correct sphere5.mesh.

Best regards，

Xiaoyu.


MrBurnst <notifications@github.com>于2019年5月24日 周五下午2:08写道：

**Comment by MrBurnst** [comment]
hi! I did not change anything to the code (just di=5 for more screenshots). I just checked out the repo yesterday and tried again, still getting only spiky spheres - here after 100, 200 and 300 iterations:
![B100](https://user-images.githubusercontent.com/4426897/60083897-d5a68900-9736-11e9-93f1-e145a59d8176.png)
![B200](https://user-images.githubusercontent.com/4426897/60083898-d5a68900-9736-11e9-85b5-8b3e0d316e66.png)
![B300](https://user-images.githubusercontent.com/4426897/60083900-d5a68900-9736-11e9-95b5-88110da47052.png)

it seems like the collision detection is not working at all... what python version / libraries are you using? I did not manage to get it to compile with numba in python3, so I'm using 2.7 with requirements

> bz2file==0.98
> enum34==1.1.6
> funcsigs==1.0.2
> llvmlite==0.28.0
> nibabel==2.4.1
> numba==0.43.1
> numpy==1.16.3
> numpy-stl==2.10.1
> pkg-resources==0.0.0
> python-utils==2.3.0
> scikit-learn==0.20.3
> scipy==1.2.1
> singledispatch==3.4.0.3
> six==1.12.0
> sklearn==0.0
> Vapory==0.1.1

and you?

**Comment by x17wang** [comment]
Hi，

I also use the version 2.7.  I’ve been out on business lately，I will check
the problem again and email you when I get back.

Best regards.

Xiaoyu.

MrBurnst <notifications@github.com>于2019年6月25日 周二上午10:51写道：

**Comment by MrBurnst** [comment]
hi... any news on this? thanks...

**Comment by x17wang** [comment]
Hi,

Sorry for the delayed response.

On my side, the codes can give the result shown in the .gif for sphere5.mesh.

With requirements:

enum34==1.1.6
funcsigs==1.0.2
llvmlite==0.24.0
nibabel==2.3.1
numba==0.39.0
numpy==1.16.2
numpy-stl==2.10.1
python-utils==2.3.0
scikit-learn==0.20.3
scipy==1.2.1
singledispatch==3.4.0.3
six==1.11.0
Vapory==0.1.1

![sphere5](https://user-images.githubusercontent.com/40798933/63592827-db8fdd80-c5b2-11e9-8d7e-5448ecb8652a.gif)

Best regards. 

Xiaoyu.

**Comment by MrBurnst** [comment]
thanks! with these requirements, it looks the same for me now as well!
